#!/usr/bin/env perl
# content/dev/misc/dnsresolvd/perl/script/dnsresolvd
# =============================================================================
# DNS Resolver Daemon (dnsresolvd). Version 0.1
# =============================================================================
# A Mojolicious-boosted daemon for performing DNS lookups.
# =============================================================================
# Copyright (C) 2017 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

use strict;
use warnings;
use utf8;
use v5.10;

use FindBin;

BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use Mojolicious::Commands;

# Starting up the app.
Mojolicious::Commands->start_app("DNSResolvd");

# vim:set nu:et:ts=4:sw=4:
