#!/usr/bin/env bash
# utils/aur-pkg-snapshots-download
# =============================================================================
# This helper script downloads package snapshots from the Arch User Repository
# (AUR) for --foreign packages currently installed on the system,
# to the current directory.
# =============================================================================
# Copyright (C) 2020 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

# Helper constants.
declare -r EXIT_FAILURE=1 #    Failing exit status.
declare -r EXIT_SUCCESS=0 # Successful exit status.

declare -r AUR_URL="https://aur.archlinux.org/cgit/aur.git/snapshot/"
declare -r PKG_EXT=".tar.gz"

for pkg_name in `pacman -Qmq`; do
    curl -LO ${AUR_URL}${pkg_name}${PKG_EXT}
done

# If there is an error -- telling the OS about this.
if [ $? -eq ${EXIT_FAILURE} ]; then
    exit    ${EXIT_FAILURE}
fi

exit        ${EXIT_SUCCESS}

# vim:set nu et ts=4 sw=4:
