#!/usr/bin/env bash
# utils/snd-files-rename
# =============================================================================
# A Cup of Radicchio. Version 0.1
# =============================================================================
# A Cup of Radicchio: A personal website of a power looper,
#                                             skateboarder,
#                                      and software devver.
#
# This helper script takes sound files in the current/specified directory
# and renames them according to a simple manifest
# where their proper names listed.
# =============================================================================
# Copyright (C) 2018 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

# Helper constants.
declare -r EXIT_FAILURE=1 #    Failing exit status.
declare -r EXIT_SUCCESS=0 # Successful exit status.

ARGC=$#
ARG0=$0
ARG1=$1
ARG2=$2

MANIFEST=/dev/null
DIR=/tmp

# Checking for args presence and validating them if any.
if [ ${ARGC} -eq 0 ]; then
    echo "Error: There must be at least one arg passed: ${ARGC} args found"
    echo "Usage: ${ARG0} <manifest_filename> [target_directory]"

    exit ${EXIT_FAILURE}
else
    MANIFEST=${ARG1}

    if [ ! -f ${MANIFEST} ]; then
        echo "Error: Given manifest file does not exist: ${MANIFEST}"

        exit ${EXIT_FAILURE}
    fi

    if [ ${ARGC} -gt 1 ]; then
        DIR=${ARG2}

        if [ ! -d ${DIR} ]; then
            echo "Error: Given directory does not exist: ${DIR}"
            echo "Using the current directory..."

            DIR=.
        fi
    fi
fi

# --- Debug output - Begin ----------------------------------------------------
echo -n "=== "; cd ${DIR}; pwd; ls -al
# --- Debug output - End ------------------------------------------------------

# If there is an error -- telling the OS about this.
if [ $? -eq ${EXIT_FAILURE} ]; then
    exit    ${EXIT_FAILURE}
fi

exit        ${EXIT_SUCCESS}

# vim:set nu et ts=4 sw=4:
