#!/usr/bin/env bash
# utils/snd-files-rename
# =============================================================================
# This helper script takes sound files in the current/specified directory
# and renames them according to a simple manifest
# where their proper names listed.
# =============================================================================
# Copyright (C) 2018-2023 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

# Helper constants.
declare -r EXIT_FAILURE=1 #    Failing exit status.
declare -r EXIT_SUCCESS=0 # Successful exit status.

ARGC=$#
ARG0=$0
ARG1=$1
ARG2=$2

MANIFEST=/dev/null
DIR=.
FILES=*.mp3

# Common error messages.
declare -r _ERR_PREFIX="Error:"
declare -r _ERR_MUST_BE_ONE_ARG_OR_MORE="There must be at least one arg "`
                                       `"passed: ${ARGC} args found"
declare -r _ERR_MANIFEST_NOT_FOUND="Given manifest file does not exist:"
declare -r _ERR_DIR_NOT_FOUND="Given directory does not exist:"
declare -r _ERR_WILL_USE_CUR_DIR="Using the current directory..."

# Print this usage info just after any inappropriate input.
declare -r _MSG_USAGE_TEMPLATE="Usage: ${ARG0} <manifest_filename> "`
                              `"[target_directory]"

# Checking for args presence and validating them if any.
if [ ${ARGC} -eq 0 ]; then
    echo ${_ERR_PREFIX} ${_ERR_MUST_BE_ONE_ARG_OR_MORE}
    echo ${_MSG_USAGE_TEMPLATE}

    exit ${EXIT_FAILURE}
else
    MANIFEST=${ARG1}

    if [ ! -f ${MANIFEST} ]; then
        echo ${_ERR_PREFIX} ${_ERR_MANIFEST_NOT_FOUND} ${MANIFEST}
        echo ${_MSG_USAGE_TEMPLATE}

        exit ${EXIT_FAILURE}
    fi

    if [ ${ARGC} -gt 1 ]; then
        DIR=${ARG2}

        if [ ! -d ${DIR} ]; then
            echo ${_ERR_PREFIX} ${_ERR_DIR_NOT_FOUND} ${DIR}
            echo ${_ERR_WILL_USE_CUR_DIR}

            DIR=.
        fi
    fi
fi

# Slurping the manifest.
manifest=$(< ${MANIFEST})

# --- Debug output - Begin ----------------------------------------------------
# Reading the manifest and printing its contents.
#while read -r line; do
#    echo ${line}
#done < ${MANIFEST}
# --- Debug output - End ------------------------------------------------------

# Splitting the manifest (into an array).
IFS=$'\n' manifest=(${manifest})

i=0

# Reading sound files and renaming them according to manifest records.
for file in ${DIR}/${FILES}; do
    mv -v ${file} ${DIR}/${manifest[i]}

    let i++
done

# If there is an error -- telling the OS about this.
if [ $? -eq ${EXIT_FAILURE} ]; then
    exit    ${EXIT_FAILURE}
fi

exit        ${EXIT_SUCCESS}

# vim:set nu et ts=4 sw=4:
