#!/usr/bin/env perl
# utils/vk-com-radicchio
# =============================================================================
# Usage:
#     $ curl -sO http://rgolubtsov.github.io/utils/vk-com-radicchio && \
#       chmod 700                                  vk-com-radicchio && \
#                                                ./vk-com-radicchio; echo $?
# =============================================================================
# This Perl script is intended to be used as an artificial database
# (or a datastore) that is holding distinct literal data, and simply
# printing them out as a whole upon its invocation. It indeed relates
# to the Radicchio VK profile, especially with their photos' captions.
# =============================================================================
# Copyright (C) 2020 Radislav (Radicchio) Golubtsov
#
# (See the LICENSE file at the top of the source tree.)
#

use strict;
use warnings;
use utf8;
use v5.10;

# -----------------------------------------------------------------------------

use constant {
    A_MODERN_DEFENDER                                                          => "Summer-2010",
    BLUE_EYED_EARRINGS_MADE_WITH_SWAROVSKI_ELEMENTS_FOR_MY_BEAUTIFUL_ELIZABETH => 1,
    A_MUG_OF_RADICCHIO                                                         => "11111001 Markov Chain",
    BLUE_GLOW_ABSTRACT                                                         => 1,
    GRAY_GRIN_ABSTRACT                                                         => 1,
    TVOE_RU_JUSTICE_LEAGUE_1                                                   => 1,
    TVOE_RU_JUSTICE_LEAGUE_2                                                   => 1,
    TVOE_RU_JUSTICE_LEAGUE_3                                                   => 1,
    TVOE_RU_JUSTICE_LEAGUE_4                                                   => 1,
    TVOE_RU_JUSTICE_LEAGUE_5                                                   => 1,
    RADICCH_IO                                                                 => 1,
    RADIC_CHIO                                                                 => 1,
    MY_KIDS                                                                    => "The only friends.",
    SWEET_KITTY_LIZY                                                           => "Fall-2013",
    SAMURAI_LOOK_LIZY                                                          => "Fall-2013",
    SMILING_KITTY_LIZY                                                         => "Fall-2013",
    YARO_FAME_YARYA                                                            => "Fall-2013",
    BRIGHT_MODEL_27_LIZY                                                       => "Fall-2013",
    DEEP_BLUE_EYES_FASCINATION_ALIKE_IS_LIZY                                   => "Fall-2013",
    TRANSFORMERS_PRIME_YARYA_LIZY                                              => "Fall-2013",
    SELF_CARE                                                                  => "A sound mind in a sound body !",
    WORKOUT_TWISTER                                                            => "Fall-2015",
    CLASSIC_ABDOMINAL_WORKOUT_TWISTER                                          => "Fall-2015",
    GENERIC_LEGS_AND_FEET_JUMPING_OUT_UPBEAT_WORKOUT_TWISTER                   => "Fall-2015",
    HULA_HOOP_TWIDDLER                                                         => "Fall-2015",
    HULA_HOOP_TWIDDLER_IN_ACTION                                               => "Fall-2015",
    LEFT_HAND_ACCESSORIES                                                      => "(1) OMAX Watch: "
                                                                                . "Japanese Mechanics / "
                                                                                . "Original Bracelet - "
                                                                                . "(2) Golden Ring - | "
                                                                                . "Fall-2015",
    WE_RE_MORE_CONSTANT_THAN_THE_GODS                                          => "Radicchio & Yaro Together(!) - | "
                                                                                . "Fall-2015",
    I_PLAY_BUTTERFLY                                                           => "Fall-2015",
    BACKHAND_LOOP_IN_ACTION                                                    => "(Using Butterfly Bryce Speed FX 2.1) - | "
                                                                                . "Fall-2015",
    WHAT_DOES_THIS_MEAN_1                                                      => "Fall-2015",
    WHAT_DOES_THIS_MEAN_2                                                      => "Fall-2015",
    WHAT_DOES_THIS_MEAN_3                                                      => "Fall-2015",
    I_WEAR                                                                     => "(1) TVOE.RU: T-shirt Basics Cloudy Sky - "
                                                                                . "(2) Joss-Wear.com: Shorts Generics Athletics - "
                                                                                . "(3) Adidas Duramo 6 M - | "
                                                                                . "Fall-2015",
    NUCLEAR_FISSION                                                            => "Fall-2015",
    WINX_AND_LIZY                                                              => "Summer-2012",
    LIZY_SPRINGTIME                                                            => "Spring-2011",
    TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_1ST_FRAME                     => "Winter-2015",
    TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_2ND_FRAME                     => "Winter-2015",
    TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_IN_ACTION                     => "Winter-2015",
    AT_THE_ITTF_WORLD_TOUR_GRAND_FINALS_1                                      => "Winter-2015",
    AT_THE_ITTF_WORLD_TOUR_GRAND_FINALS_2                                      => "Winter-2015",
    AT_THE_IBA_TABLE_TENNIS_CHAMPIONSHIP_1                                     => "Spring-2011",
    AT_THE_IBA_TABLE_TENNIS_CHAMPIONSHIP_2                                     => "Spring-2011",
    WEARING_ASICS_1                                                            => "Summer-2012",
    DRINKING_TEAX_CEYLON_BLACK_TEA_OP                                          => "Summer-2012",
    A_MODERN_METROSEXUAL                                                       => "Summer-2010",
    A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_1                                       => "Summer-2010",
    A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_2                                       => "Summer-2010",
    A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_3                                       => "Summer-2010",
    AT_KLIONKOVSKY_BRIDGE                                                      => "Summer-2012",
    A_MODERN_DEFENDER_1                                                        => "(Chopping using Milky Way Neptune 1.0) - | "
                                                                                . "Summer-2010",
    A_MODERN_DEFENDER_2                                                        => "(Chopping using Milky Way Neptune 1.0) - | "
                                                                                . "Summer-2010",
    A_MODERN_DEFENDER_3                                                        => "(Looping using Butterfly Tackiness-C 1.7) - | "
                                                                                . "Summer-2010",
    A_MODERN_DEFENDER_4                                                        => "(Looping using Butterfly Tackiness-C 1.7) - | "
                                                                                . "Summer-2010",
    LIZY_AND_SPOON                                                             => "Winter-2008",
    LIZY_KHTOSKA_IS_LOOKING_LIKE_1                                             => "Babus'ka... && Yaro together - | "
                                                                                . "Spring-2009",
    LIZY_KHTOSKA_IS_LOOKING_LIKE_2                                             => "Babus'ka... && Yaro together - | "
                                                                                . "Spring-2009",
    RADICCHIO_AND_YARO_TOGETHER                                                => "Winter-2007",
    RADICCHIO_AND_YARO_TOGETHER_LOOP_THEM_ALL                                  => "Winter-2008",
    ROBIN_HOOD_PLUS_MAID_MARIAN_PLUS_LITTLE_JOHN_1                             => "Spring-2009",
    ROBIN_HOOD_PLUS_MAID_MARIAN_PLUS_LITTLE_JOHN_2                             => "Spring-2009",
    DRINKING_VODKA                                                             => "(Authentic Crystal Byelorussian Vodka) - | "
                                                                                . "Summer-2012",
    RIDING_ARCTIX_PLUS_WEARING_ASICS                                           => "Summer-2012",
    WEARING_ASICS_PLUS_WEARING_PUMA                                            => "Summer-2012",
    WEARING_ASICS_2                                                            => "Summer-2012",
    TARTANISH                                                                  => "Spring-2012",
    TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_1                                   => "(Using Butterfly Maze Passion OFF- (Fiberglass) "
                                                                                . "and Donic Vario 1.8 on both sides) - | "
                                                                                . "Fall-2009",
    TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_2                                   => "(Using Butterfly Maze Passion OFF- (Fiberglass) "
                                                                                . "and Donic Vario 1.8 on both sides) - | "
                                                                                . "Fall-2009",
    TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_3                                   => "(Using Butterfly Maze Passion OFF- (Fiberglass) "
                                                                                . "and Donic Vario 1.8 on both sides) - | "
                                                                                . "Fall-2009",
    MICHAEL_MAZE_IS                                                            => "[ My irreversible TT-idol ]",
    A_DEVICEPROS_MODEL_1                                                       => "Summer-2016",
    A_DEVICEPROS_MODEL_2                                                       => "Summer-2016",
    TRY_TO_FIND_EIGHT_DISTINCTIONS                                             => "Summer-2016",
    A_PROUD_DAD_OF_LIZY_AND_YARO                                               => "Summer-2016",
    A_DEVICEPROS_MODEL_3_SK8ER_BOI_HVD_1_1                                     => "Spring-2016",
    A_DEVICEPROS_MODEL_4_SK8ER_BOI_HVD_1_2                                     => "Spring-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_1                                           => "Summer-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_2                                           => "Summer-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_3                                           => "Summer-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_4                                           => "Summer-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_5                                           => "Summer-2016",
    AN_ANTHOCYANIN_BLUE_HAIR_MODEL_6                                           => "Summer-2016",
};

# -----------------------------------------------------------------------------

say(
        "==> " . A_MODERN_DEFENDER
    . "\n==> " . BLUE_EYED_EARRINGS_MADE_WITH_SWAROVSKI_ELEMENTS_FOR_MY_BEAUTIFUL_ELIZABETH
    . "\n==> " . A_MUG_OF_RADICCHIO
    . "\n==> " . BLUE_GLOW_ABSTRACT
    . "\n==> " . GRAY_GRIN_ABSTRACT
    . "\n==> " . TVOE_RU_JUSTICE_LEAGUE_1
    . "\n==> " . TVOE_RU_JUSTICE_LEAGUE_2
    . "\n==> " . TVOE_RU_JUSTICE_LEAGUE_3
    . "\n==> " . TVOE_RU_JUSTICE_LEAGUE_4
    . "\n==> " . TVOE_RU_JUSTICE_LEAGUE_5
    . "\n==> " . RADICCH_IO
    . "\n==> " . RADIC_CHIO
    . "\n==> " . MY_KIDS
    . "\n==> " . SWEET_KITTY_LIZY
    . "\n==> " . SAMURAI_LOOK_LIZY
    . "\n==> " . SMILING_KITTY_LIZY
    . "\n==> " . YARO_FAME_YARYA
    . "\n==> " . BRIGHT_MODEL_27_LIZY
    . "\n==> " . DEEP_BLUE_EYES_FASCINATION_ALIKE_IS_LIZY
    . "\n==> " . TRANSFORMERS_PRIME_YARYA_LIZY
    . "\n==> " . SELF_CARE
    . "\n==> " . WORKOUT_TWISTER
    . "\n==> " . CLASSIC_ABDOMINAL_WORKOUT_TWISTER
    . "\n==> " . GENERIC_LEGS_AND_FEET_JUMPING_OUT_UPBEAT_WORKOUT_TWISTER
    . "\n==> " . HULA_HOOP_TWIDDLER
    . "\n==> " . HULA_HOOP_TWIDDLER_IN_ACTION
    . "\n==> " . LEFT_HAND_ACCESSORIES
    . "\n==> " . WE_RE_MORE_CONSTANT_THAN_THE_GODS
    . "\n==> " . I_PLAY_BUTTERFLY
    . "\n==> " . BACKHAND_LOOP_IN_ACTION
    . "\n==> " . WHAT_DOES_THIS_MEAN_1
    . "\n==> " . WHAT_DOES_THIS_MEAN_2
    . "\n==> " . WHAT_DOES_THIS_MEAN_3
    . "\n==> " . I_WEAR
    . "\n==> " . NUCLEAR_FISSION
    . "\n==> " . WINX_AND_LIZY
    . "\n==> " . LIZY_SPRINGTIME
    . "\n==> " . TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_1ST_FRAME
    . "\n==> " . TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_2ND_FRAME
    . "\n==> " . TABLE_TENNIS_ON_ANOTHER_PLANET_LOOP_THEM_ALL_IN_ACTION
    . "\n==> " . AT_THE_ITTF_WORLD_TOUR_GRAND_FINALS_1
    . "\n==> " . AT_THE_ITTF_WORLD_TOUR_GRAND_FINALS_2
    . "\n==> " . AT_THE_IBA_TABLE_TENNIS_CHAMPIONSHIP_1
    . "\n==> " . AT_THE_IBA_TABLE_TENNIS_CHAMPIONSHIP_2
    . "\n==> " . WEARING_ASICS_1
    . "\n==> " . DRINKING_TEAX_CEYLON_BLACK_TEA_OP
    . "\n==> " . A_MODERN_METROSEXUAL
    . "\n==> " . A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_1
    . "\n==> " . A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_2
    . "\n==> " . A_SK8ER_BOI_4EVER_BY_AVRIL_LAVIGNE_3
    . "\n==> " . AT_KLIONKOVSKY_BRIDGE
    . "\n==> " . A_MODERN_DEFENDER_1
    . "\n==> " . A_MODERN_DEFENDER_2
    . "\n==> " . A_MODERN_DEFENDER_3
    . "\n==> " . A_MODERN_DEFENDER_4
    . "\n==> " . LIZY_AND_SPOON
    . "\n==> " . LIZY_KHTOSKA_IS_LOOKING_LIKE_1
    . "\n==> " . LIZY_KHTOSKA_IS_LOOKING_LIKE_2
    . "\n==> " . RADICCHIO_AND_YARO_TOGETHER
    . "\n==> " . RADICCHIO_AND_YARO_TOGETHER_LOOP_THEM_ALL
    . "\n==> " . ROBIN_HOOD_PLUS_MAID_MARIAN_PLUS_LITTLE_JOHN_1
    . "\n==> " . ROBIN_HOOD_PLUS_MAID_MARIAN_PLUS_LITTLE_JOHN_2
    . "\n==> " . DRINKING_VODKA
    . "\n==> " . RIDING_ARCTIX_PLUS_WEARING_ASICS
    . "\n==> " . WEARING_ASICS_PLUS_WEARING_PUMA
    . "\n==> " . WEARING_ASICS_2
    . "\n==> " . TARTANISH
    . "\n==> " . TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_1
    . "\n==> " . TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_2
    . "\n==> " . TABLE_TENNIS_RACKET_ASSEMBLY_IN_ACTION_3
    . "\n==> " . MICHAEL_MAZE_IS
    . "\n==> " . A_DEVICEPROS_MODEL_1
    . "\n==> " . A_DEVICEPROS_MODEL_2
    . "\n==> " . TRY_TO_FIND_EIGHT_DISTINCTIONS
    . "\n==> " . A_PROUD_DAD_OF_LIZY_AND_YARO
    . "\n==> " . A_DEVICEPROS_MODEL_3_SK8ER_BOI_HVD_1_1
    . "\n==> " . A_DEVICEPROS_MODEL_4_SK8ER_BOI_HVD_1_2
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_1
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_2
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_3
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_4
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_5
    . "\n==> " . AN_ANTHOCYANIN_BLUE_HAIR_MODEL_6
);

# vim:set nu et ts=4 sw=4:
